# Generated by Django 2.1.4 on 2019-01-03 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('client_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('external_ip', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('internal_ip', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('gateway', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('network_mask', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('authorized', models.BooleanField(default=False)),
                ('last_seen', models.DateField(blank=True, default=None, null=True)),
                ('creation', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
